/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AiChatBox: typeof import('./src/components/AiChatBox.vue')['default']
    DispatchPendingList: typeof import('./src/components/DispatchPendingList.vue')['default']
    EchartItem: typeof import('./src/components/EchartItem.vue')['default']
    EchartTitle: typeof import('./src/components/EchartTitle.vue')['default']
    EmergencyResponsePanel: typeof import('./src/components/EmergencyResponsePanel.vue')['default']
    Head: typeof import('./src/components/Head.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MapSearch: typeof import('./src/components/MapSearch.vue')['default']
    MenuTabs: typeof import('./src/components/MenuTabs.vue')['default']
    Popup: typeof import('./src/components/Popup.vue')['default']
    Progress: typeof import('./src/components/Progress.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
